development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: animecult
  pool: 5
  username: postgres
  password: <%= ENV['PG_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: animecult
  pool: 5
  username: postgres
  password: <%= ENV['PG_PASSWORD'] %>
